spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  application.name: rental

server:
  port: 8060
#  servlet.context-path: /api/v1

logging:
  level:
    ru.bmstu: TRACE

rentalapi:
  url:
    base: "/api/v1/rental"