spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  application.name: cars
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: 8070
#  servlet.context-path: /api/v1

logging:
  level:
    ru.bmstu: TRACE

carsapi:
  url:
    base: /api/v1/cars